### ISSUE TITLE
Keep getting 'SyntaxError: Unexpected token =' when using in Console

### ISSUE THREAD

**Issue by M0S4YSH3LL0** [elliotttf/jsonapi-validator#67]

**Comment by elliotttf** [comment]
Can you give me an example of the file you're trying to validate?

**Comment by M0S4YSH3LL0** [comment]
> jsonapi-valiadtor -f sample-output.json


sample-output.json contains:

> {
    "data": {
        "type": "worker",
        "id": "1",
        "attributes": {
            "forename": "Test",
            "surname": "BüttnerDerZweite",
            "wrk_worker_id": 1
        },
        "links": {
            "self": {
                "href": "http://127.0.0.1:8000/api/v2/worker/1"
            },
            "hardware": {
                "href": "http://127.0.0.1:8000/api/v2/worker/1/hardware"
            },
            "software": {
                "href": "http://127.0.0.1:8000/api/v2/worker/1/software"
            },
            "inventory": {
                "href": "http://127.0.0.1:8000/api/v2/worker/1/inventory"
            },
            "accessory": {
                "href": "http://127.0.0.1:8000/api/v2/worker/1/accessory"
            }
        },
        "relationships": {
            "department": {
                "data": {
                    "type": "department",
                    "id": "1"
                }
            },
            "room": {
                "data": {
                    "type": "room",
                    "id": "1"
                }
            },
            "hardware": {
                "data": [
                    {
                        "type": "hardware",
                        "id": "TEST123"
                    }
                ]
            },
            "inventory": {
                "data": [
                    {
                        "type": "inventory",
                        "id": "INV0001"
                    },
                    {
                        "type": "inventory",
                        "id": "INV0005"
                    }
                ]
            },
            "accessory": {
                "data": [
                    {
                        "type": "accessory",
                        "id": "ACC0002"
                    },
                    {
                        "type": "accessory",
                        "id": "ACC0001"
                    }
                ]
            },
            "softwarelicence": {
                "data": [
                    {
                        "type": "licence",
                        "id": "SW4321"
                    }
                ]
            }
        }
    },
    "included": [
        {
            "type": "department",
            "id": "1",
            "attributes": {
                "department": "Entwicklung",
                "dept_floor_id": 3
            },
            "links": {
                "self": {
                    "href": "http://127.0.0.1:8000/api/v2/department/1"
                },
                "floor": {
                    "href": "http://127.0.0.1:8000/api/v2/floor/3"
                },
                "hardware": {
                    "href": "http://127.0.0.1:8000/api/v2/department/1/hardware"
                },
                "software": {
                    "href": "http://127.0.0.1:8000/api/v2/department/1/software"
                },
                "inventory": {
                    "href": "http://127.0.0.1:8000/api/v2/department/1/inventory"
                },
                "accessory": {
                    "href": "http://127.0.0.1:8000/api/v2/department/1/accessory"
                }
            }
        },
        {
            "type": "room",
            "id": "1",
            "attributes": {
                "room": "Entwickler-Büro",
                "room_floor_id": 3
            },
            "links": {
                "self": {
                    "href": "http://127.0.0.1:8000/api/v2/room/1"
                },
                "floor": {
                    "href": "http://127.0.0.1:8000/api/v2/floor/3"
                }
            }
        },
        {
            "type": "hardware",
            "id": "TEST123",
            "attributes": {
                "hw_type": "Monitor",
                "hw_description": "LG FLATRON",
                "hw_serialkey": "11whatever11",
                "hw_bill": null,
                "hw_user_worker_id": 1,
                "hw_user_department_id": 2,
                "hw_owner_department_id": 2,
                "hw_owner_company_id": 1
            },
            "links": {
                "self": {
                    "href": "http://127.0.0.1:8000/api/v2/hardware/TEST123"
                },
                "user": {
                    "href": "http://127.0.0.1:8000/api/v2/worker/1"
                },
                "owner_dept": {
                    "href": "http://127.0.0.1:8000/api/v2/department/2"
                },
                "owner_comp": {
                    "href": "http://127.0.0.1:8000/api/v2/company/1"
                }
            }
        },
        {
            "type": "inventory",
            "id": "INV0001",
            "attributes": {
                "inv_description": "test",
                "inv_owner_department_id": 1,
                "inv_user_department_id": 1,
                "inv_user_worker_id": 1,
                "inv_owner_company_id": 1
            },
            "links": {
                "self": {
                    "href": "http://127.0.0.1:8000/api/v2/inventory/INV0001"
                },
                "user": {
                    "href": "http://127.0.0.1:8000/api/v2/worker/1"
                },
                "owner_dept": {
                    "href": "http://127.0.0.1:8000/api/v2/department/1"
                },
                "owner_comp": {
                    "href": "http://127.0.0.1:8000/api/v2/company/1"
                }
            }
        },
        {
            "type": "inventory",
            "id": "INV0005",
            "attributes": {
                "inv_description": "POST test",
                "inv_owner_department_id": 1,
                "inv_user_department_id": 1,
                "inv_user_worker_id": 1,
                "inv_owner_company_id": 1
            },
            "links": {
                "self": {
                    "href": "http://127.0.0.1:8000/api/v2/inventory/INV0005"
                },
                "user": {
                    "href": "http://127.0.0.1:8000/api/v2/worker/1"
                },
                "owner_dept": {
                    "href": "http://127.0.0.1:8000/api/v2/department/1"
                },
                "owner_comp": {
                    "href": "http://127.0.0.1:8000/api/v2/company/1"
                }
            }
        },
        {
            "type": "accessory",
            "id": "ACC0002",
            "attributes": {
                "acc_description": "TESTInventar",
                "acc_serialkey": "TESTSERIAL",
                "acc_bill": null,
                "acc_owner_company_id": 1,
                "acc_owner_department_id": 1,
                "acc_user_worker_id": 1,
                "acc_user_department_id": 1
            },
            "links": {
                "self": {
                    "href": "http://127.0.0.1:8000/api/v2/inventory/ACC0002"
                },
                "user": {
                    "href": "http://127.0.0.1:8000/api/v2/worker/1"
                },
                "owner_dept": {
                    "href": "http://127.0.0.1:8000/api/v2/department/1"
                },
                "owner_comp": {
                    "href": "http://127.0.0.1:8000/api/v2/company/1"
                }
            }
        },
        {
            "type": "accessory",
            "id": "ACC0001",
            "attributes": {
                "acc_description": "test",
                "acc_serialkey": "asfsaf",
                "acc_bill": null,
                "acc_owner_company_id": 1,
                "acc_owner_department_id": 1,
                "acc_user_worker_id": 1,
                "acc_user_department_id": 1
            },
            "links": {
                "self": {
                    "href": "http://127.0.0.1:8000/api/v2/inventory/ACC0001"
                },
                "user": {
                    "href": "http://127.0.0.1:8000/api/v2/worker/1"
                },
                "owner_dept": {
                    "href": "http://127.0.0.1:8000/api/v2/department/1"
                },
                "owner_comp": {
                    "href": "http://127.0.0.1:8000/api/v2/company/1"
                }
            }
        },
        {
            "type": "licence",
            "id": "SW4321",
            "attributes": {
                "sw_description": "12341243",
                "sw_licencekey": "LK4321",
                "sw_worker_id": 1
            },
            "links": {
                "self": {
                    "href": "http://127.0.0.1:8000/api/v2/softwarelicence/SW4321"
                },
                "user": {
                    "href": "http://127.0.0.1:8000/api/v2/worker/1"
                }
            }
        }
    ],
    "links": {
        "hardware": {
            "href": "http://127.0.0.1:8000/api/v2/worker/1/hardware"
        },
        "software": {
            "href": "http://127.0.0.1:8000/api/v2/worker/1/software"
        },
        "inventory": {
            "href": "http://127.0.0.1:8000/api/v2/worker/1/inventory"
        },
        "accessory": {
            "href": "http://127.0.0.1:8000/api/v2/worker/1/accessory"
        },
        "self": {
            "href": "http://127.0.0.1:8000/api/v2/worker/1"
        }
    },
    "jsonapi": {
        "version": "1.0"
    }
}

**Comment by elliotttf** [comment]
Hmm, I'm not able to reproduce the invalid token error you've noted. Which version of the module are you using and which version of node are you on?

**Comment by M0S4YSH3LL0** [comment]
Solved!

The 'Unexpected Token =' was produced from the constructer-function in validator.js

Changed this
```
  constructor(schema = defaultSchema) {
    this.validator = ajv.compile(schema);
  }
```

to

```
  constructor() {
    this.validator = ajv.compile(defaultSchema);
  }
```

**Comment by elliotttf** [comment]
Ah ok, that's because of the version of node you're using. You'll need to be running 6 or later which adds support for default parameter values.

Alternatively, downgrade to one of the 1.x versions of the module (but note that it is no longer being supported by me).

**Comment by M0S4YSH3LL0** [comment]
Thank you !
I updated to v7.4.0 and now it's working like a charm with default parameter values :)
