### ISSUE TITLE
Does release 3.0.3 need to reference JSON-Schema draft-06?

### ISSUE THREAD

**Issue by ghost** [elliotttf/jsonapi-validator#83]
Hello,

I've just updated a project to use the latest version of "jsonapi-validator", but am now seeing failures.

I've taken a look and suspect that this is being caused by the validator using a embedded JSONAPI schema, which has been changed to use "uri-reference" (rather than "uri") for some properties. However, the schema being referenced appears to still be "draft-04", whereas it looks like "uri-reference" is only available in "draft-06"?

There appears to be a dependency on version "4.1.3" of the "ajv" package, whereas it looks like "jsonapi-validator" may need to reference version "5.x" in order to support JSON-Schema "draft-06"?

Having said all that, it looks like the JSON-Schema referenced by JSONAPI itself may have a similar problem, as it also uses "uri-reference" while still pointing at "draft-04":

    http://jsonapi.org/schema

Thoughts?

**Comment by ghost** [comment]
Appears to be related to this change:

  https://github.com/json-api/json-api/pull/1160

**Comment by elliotttf** [comment]
Thanks for the detailed issue! The schema deployed with this module is indeed a straight pull from the json-api repository so the problem will exist there. Regardless, I'll help track this down over there and will apply the fix here as soon as possible.

**Comment by ghost** [comment]
Brilliant - thanks for the quick resolution!
