### ISSUE TITLE
Valid no-resource being not valid

### ISSUE THREAD

**Issue by ShadowManu** [elliotttf/jsonapi-validator#9]
Hi. Before everything, nice project. I've stumbled with an scenario valid by the JSON spec, but not in the validator.

In this [link at the spec](http://jsonapi.org/format/#fetching-resources-responses-404) (above it), its an example where trying to fetch a specific resource that doesn't exist (yet), it is valid for the server to return `null` as the primary data. More specifically:

``` javascript
{
  "links": {
    "self": "http://example.com/articles/1/author"
  },
  "data": null
}
```

I just copied the `links` part too as in the example, but being `{ "data": null }` is a sufficient response too.

**Comment by elliotttf** [comment]
Good catch! I think you meant to link [here](http://jsonapi.org/format/#fetching-resources-responses-200)? Specifically:

> A server **MUST** respond to a successful request to fetch an individual resource with a resource object or `null` provided as the response document's primary data.
> 
> `null` is only an appropriate response when the requested URL is one that might correspond to a single resource, but doesn't currently.

This appears to be a problem with JSON API's [schema document](https://github.com/json-api/json-api/blob/gh-pages/schema#L105) which this module relies on. I'll check for an issue in their repository for this and if one doesn't exist will open a new one.

Thanks for contributing!

**Comment by ShadowManu** [comment]
Yeah, was not the best link but that's the text I was referring to. I'm
starting to see how I can help the packages I use little by little.
